version: "3.3"

services:
  mongodb:
    image: mongo:5.0
    container_name: ${PROJECT} 
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: